### ISSUE TITLE
Objects are not referenced like ES6 Maps are

### ISSUE THREAD

**Issue by cronvel** [jhuckaby/megahash#3]
Hi,

It looks like the objects stored are somewhat serialized, instead of storing object references, so it's not a dropping replacement for ES6 Map.
Is that a bug or an undocumented feature?

E.g.:
```js
const Hmap = require( 'megahash' ) ;
hmap = new Hmap() ;

var o = { a: 1 } ;
hmap.set( 'key' , o ) ;
console.log( hmap.get( 'key' ) === o ) ;  // expected true, but got false
console.log( hmap.get( 'key' ) ) ;
o.b = 2 ;
console.log( hmap.get( 'key' ) ) ;  // expected {a:1,b:2} but got {a:1}
```

**Comment by jhuckaby** [comment]
I do apologize, but this is as designed.  It is documented here:

https://github.com/jhuckaby/megahash#objects

Objects have to be serialized because they are stored "off" of the V8 heap, and in C++ land.  If you need something that stores native objects on the heap, you might want to look at the npm [hashtable](https://www.npmjs.com/package/hashtable) module.

Megahash was not really meant to be a *drop-in replacement* for ES6 Maps.  I will change the docs to make this more clear.  Sorry for the confusion!

**Comment by jhuckaby** [comment]
Added a [caveats](https://github.com/jhuckaby/megahash#caveats) section to the doc, and linked to it from the intro paragraph.

**Comment by cronvel** [comment]
@jhuckaby Thanks for the reply ;)

BTW how does the lib perform compared to ES6 Map when all values are always object? Let's say values are typical DB document of around 10-15 keys. I'm specifically interested to know where the ES6 Map perf drop below Megahash for this use case. Have you data on that?

**Comment by jhuckaby** [comment]
No problem.

I have never performed such a test.  I will do it as soon as I have some time, but I'll wager that ES6 Map will be like a thousand times faster, because it's storing the object natively instead of translating it to/from JSON.  I think for that use case Megahash would only really be of any use to you if you are storing hundreds of millions of keys, which is where ES6 Map falls over.  So MGH wouldn't win on speed at all, but it would win on total keys. 🤷‍♂

**Comment by cronvel** [comment]
@jhuckaby Ok thanks for all those informations! ;)
