### ISSUE TITLE
question about maintenance status and xxHash

### ISSUE THREAD

**Issue by timotejroiko** [jhuckaby/megahash#9]
Hello, I am interested in this project and would like to contribute, is it still actively maintained? I see a few PRs have been open for a while...

I would also like to ask, have you experimented with the xxHash algorithm? While they claim it to be the fastest hashing algorithm around, current JS implementations pale in comparison to DJB and FNV but implementing it in C++ could be an interesting thing to test.

Regards!

**Comment by jhuckaby** [comment]
Hi there!  Thank you for the interest in MegaHash!

Yes, this module is still actively maintained, but I consider it to be "stable" at this point.  Meaning, I don't have any major plans for big future updates except for maintenance (performance improvements, compatibility with future Node.js runtimes, possibly pre-compiled binaries if I can figure out how to do that, etc.).  That's basically the extent of my roadmap, haha 😊 

I am interested in various ways to improve performance and reduce memory consumption, if it doesn't overcomplicate the code.  My big thing is that I have to understand all of the code to maintain it, and it needs to compile easily on all platforms.  That's the main reason why I chose the [DJB2](http://www.cs.yorku.ca/~oz/hash.html) hash algorithm -- because it is so simple, easy to understand, very fast, compiles everywhere, and seems to perform beautifully in all my testing.  I have not looked at xxHash, and would be curious to see if it outperforms DJB2, but in all honesty I spent about a month testing various algorithms, and all of them suffered from enormous complexity.  Not only code complexity, but also compiler / platform requirements.

My goal for the C++ portion of MegaHash is to stay as simple as possible, and be widely compatible.  When I saw DJB2, I was like "YES!  This is for me."  I mean, just look at it:

https://github.com/jhuckaby/megahash/blob/master/MegaHash.h#L221-L225

It's just so simple and elegant.  I absolutely love it.  And it would compile on a 286 😝 

As for the PRs, I didn't merge them for various reasons.  PR #6 wasn't merged because I have absolutely no knowledge or interest in TypeScript, and I didn't want the overhead of maintaining a type definitions file which I knew nothing about.  PR #7 is actually totally valid, but it isn't causing an issue (JS ignores the extra `break;`), and I just haven't had time to click the merge button.  I will do so right now.  PR #8 wasn't merged because it would break the API.  I really don't want to make any API changes at this point.

Anyway, that's where I'm at.  I do plan on actively maintaining MegaHash, as I am using it myself in a number of projects, but I don't want to make any huge changes.  But I am open to contributions, if they keep it simple 😉 

Thanks again!

**Comment by timotejroiko** [comment]
Thanks for the detailed reply :)

I completely understand your reasoning.

About typescript, I am also not a typescript user, but i have learned that typings are a great addition to all libraries for several reasons, including compatibility for TS users (which would somewhat fit into the goal of running anywhere) and great intellisense support for code editors. I understand not wanting to maintain them, but its something that could be easily maintained by someone else if you ever feel like allowing it (although i dont particularly agree with PR #6).

Besides that, i had a few ideas in mind, for instance implementing the iterator protocol for compatibility with the Map api, adding a couple more flags to avoid wasting memory and support more data types, solving the JSON.stringify issue and microbenchmarking some stuff...

Im assuming you're using `var` instead of `let` and `const` for compatibility reasons?

Anyways, i'll look into perhaps preparing some PRs later and see if you have any interest in them.

Thanks for the great work, this library is currently using 3x less memory than native Maps and Objects in my use cases.

**Comment by jhuckaby** [comment]
You make a very good point about TypeScript type definitions.  I myself use VS Code now, and I would also probably benefit from them.  I guess I just don't like the connection to the (in my experience anyway) rather aggressive and cult-like TypeScript community.  I just wish the concept of type definitions were more of an open JS standard, instead of a TypeScript thing.  I also don't really like the addition of yet another file that has to live in the root project folder.  But I'll definitely reconsider it.  It seems beneficial.

Sure thing, please feel free to work on whatever you'd like.  Iterators sound like a great addition that wouldn't break the API. 
 Just, please don't feel bad if I won't merge every PR.  I am very particular about merging into the main branch, and I need to **fully** understand and grok the code in order to maintain it.  Also, for MegaHash in particular, I have to be **very** careful about performance and memory usage, as those are its key features.  Those cannot ever regress.

Yup, the use of `var` is merely for legacy compatibility.  But I am willing to part with it at this point.  ES5 is ubiquitous.

Thanks again!
